animals/urls.py
from django.urls import path
from animals.views import index


app_name = 'animals'
urlpatterns = [
    path('', index, name='index')
]

setup/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('animals.urls')),
]

animals/models.py
from django.db import models


class Animal(models.Model):
    name = models.CharField("Nome do Animal", max_length=50)
    predador = models.BooleanField("Predador")
    poisonous = models.BooleanField("Venenoso")
    domestic = models.BooleanField("Doméstico")

    def __str__(self):
        return self.name

animals/views.py
from django.shortcuts import render
from animals.models import Animal


def index(request):
    if request.method == 'POST':
        sought_animal = request.POST['buscar']
        animals = Animal.objects.all().filter(name__icontains=sought_animal)
        context = {'animals': animals}
        return render(request, 'animals/index.html', context)
    else:
        return render(request, 'animals/index.html')

templates/animals/index.html
{% extends 'template_base.html' %}

{% block content %}


        {% for animal in animals %}
    <section class="results-section">
      <ul class="results">
        <li class="result">
          <h3 class="result-description">
            Nome do animal
          </h3>
          <h2 class="result-title">
            {{ animal.name }}
          </h2>
        </li>
        <li class="result">
          <h2 class="result-description">
            Predador
          </h2>
          <h3 class="result-description">
            {% if animal.predador%}
              {{ 'Sim' }}
            {% else %}
              {{ 'Não' }}
            {% endif %}
          </h3>
        </li>
        <li class="result">
          <h2 class="result-description">
            Venenoso
          </h2>
          <h3 class="result-description">
            {% if animal.poisonous %}
              {{ 'Sim' }}
            {% else %}
              {{ 'Não' }}
            {% endif %}
          </h3>
        </li>
        <li class="result">
          <h2 class="result-description">
            Doméstico
          </h2>
          <h3 class="result-description">
            {% if animal.domestic %}
              {{ 'Sim' }}
            {% else %}
              {{ 'Não' }}
            {% endif %}
          </h3>
        </li>
      </ul>
    </section>
{% endfor %}
{% endblock %}

templates/template_base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="shortcut icon" href="https://cdn.iconscout.com/icon/premium/png-256-thumb/lion-83-877087.png"
          type="image/x-icon">
    <title>Busca Animal</title>
</head>
<body>
    <header>
        <nav class="navbar">
      <a class="navbar__link" href="{% url 'animals:index' %}">Busca Animal</a>
        </nav>

    <section class="search-section">
        <h1 class="title">Pesquise um animal e descubra <span class="title__detail">4 coisas</span> sobre ele</h1>

        <form class="form" action="{% url 'animals:index' %}" method="POST">
            {% csrf_token %}
          <input class="form__input form-control" type="text" id="buscar-animal" name="buscar" placeholder="Exemplo: leão, urso..." aria-label="Buscar animal"/>

          <button type="submit" class="button">Pesquisar</button>
        </form>
    </section>
    </header>
    {% block content %}

    {% endblock %}





</body>
</html>